name: ecommerce_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  # get: ^4.6.6
  flutter_riverpod: ^2.5.1
  connectivity_wrapper: ^1.1.4
  app_settings: ^5.1.1
  gap: ^3.0.1
  page_transition: ^2.1.0
  flutter_svg: ^2.0.10+1
  device_preview: ^1.1.0
  pinput: ^5.0.0
  cached_network_image: ^3.3.1
  flutter_form_builder: ^9.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_html: ^3.0.0-beta.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/font/Mulish-Regular.ttf
        - asset: assets/font/Mulish-Medium.ttf
        - asset: assets/font/Mulish-bold.ttf
        - asset: assets/font/Mulish-light.ttf
        - asset: assets/font/Mulish-Italic.ttf
